# Generated by Django 3.1.1 on 2021-03-29 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField(default=0)),
                ('col', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('parking_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.parkinglotmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=13)),
                ('age', models.PositiveIntegerField(db_index=True)),
                ('park_in_time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Occupied'), (2, 'Vacant')], default=1)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.spot')),
            ],
        ),
    ]
